package config

const Version = "stave.config/v1"

// SchemaPath is the checked-in JSON Schema for the public configuration DTO.
// Keep this alongside the version constants so generators and consumers do not
// drift to a second, implicit schema location.
const SchemaPath = "schema/config/config.json"

var Required = []string{
	"schemaVersion",
	"app",
	"theme",
	"viewport",
	"capabilities",
	"keymap",
	"runtime",
	"protocol",
	"security",
	"diagnostics",
}

var JSONPaths = []string{
	"schemaVersion",
	"app.id",
	"app.version",
	"theme.id",
	"theme.mode",
	"theme.density",
	"viewport.width",
	"viewport.height",
	"capabilities.color",
	"capabilities.unicode",
	"capabilities.motion",
	"capabilities.mouse",
	"capabilities.alternateScreen",
	"keymap.profile",
	"keymap.bindings",
	"runtime.mode",
	"runtime.inputQueue",
	"runtime.actionQueue",
	"runtime.restoreOnPanic",
	"protocol.enabled",
	"protocol.transport",
	"protocol.maxMessageBytes",
	"security.allowClipboard",
	"security.allowCoordinateFallback",
	"security.confirmationTTL",
	"security.maxTreeNodes",
	"diagnostics.level",
	"diagnostics.format",
}

var EnvKeys = []string{
	"STAVE_APP_ID",
	"STAVE_APP_VERSION",
	"STAVE_THEME_ID",
	"STAVE_THEME_MODE",
	"STAVE_THEME_DENSITY",
	"STAVE_VIEWPORT_WIDTH",
	"STAVE_VIEWPORT_HEIGHT",
	"STAVE_CAPABILITIES_COLOR",
	"STAVE_CAPABILITIES_UNICODE",
	"STAVE_CAPABILITIES_MOTION",
	"STAVE_CAPABILITIES_MOUSE",
	"STAVE_CAPABILITIES_ALTERNATE_SCREEN",
	"STAVE_KEYMAP_PROFILE",
	"STAVE_RUNTIME_MODE",
	"STAVE_RUNTIME_INPUT_QUEUE",
	"STAVE_RUNTIME_ACTION_QUEUE",
	"STAVE_RUNTIME_RESTORE_ON_PANIC",
	"STAVE_PROTOCOL_ENABLED",
	"STAVE_PROTOCOL_TRANSPORT",
	"STAVE_PROTOCOL_MAX_MESSAGE_BYTES",
	"STAVE_SECURITY_ALLOW_CLIPBOARD",
	"STAVE_SECURITY_ALLOW_COORDINATE_FALLBACK",
	"STAVE_SECURITY_CONFIRMATION_TTL",
	"STAVE_SECURITY_MAX_TREE_NODES",
	"STAVE_DIAGNOSTICS_LEVEL",
	"STAVE_DIAGNOSTICS_FORMAT",
}

var FlagKeys = []string{
	"app.id",
	"app.version",
	"theme.id",
	"theme.mode",
	"theme.density",
	"viewport.width",
	"viewport.height",
	"capabilities.color",
	"capabilities.unicode",
	"capabilities.motion",
	"capabilities.mouse",
	"capabilities.alternateScreen",
	"keymap.profile",
	"runtime.mode",
	"runtime.inputQueue",
	"runtime.actionQueue",
	"runtime.restoreOnPanic",
	"protocol.enabled",
	"protocol.transport",
	"protocol.maxMessageBytes",
	"security.allowClipboard",
	"security.allowCoordinateFallback",
	"security.confirmationTTL",
	"security.maxTreeNodes",
	"diagnostics.level",
	"diagnostics.format",
}
