name: ci
on: [push, pull_request]
jobs:
  go:
    runs-on: stave-arc
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
      - uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff # v5
        with:
          go-version: '1.22'
          cache: false
      - run: test -z "$(gofmt -l .)"
      - run: go vet ./...
      - run: go test ./...
      - name: Install race detector toolchain
        run: |
          sudo apt-get update
          sudo apt-get install --no-install-recommends --yes gcc libc6-dev
      - run: go test -race ./...
        env:
          CGO_ENABLED: 1
